// ❗ You don't need to add extra action types to achieve MVP
export const MOVE_CLOCKWISE = 'MOVE_CLOCKWISE'
export const MOVE_COUNTERCLOCKWISE = 'MOVE_COUNTERCLOCKWISE'
export const SET_QUIZ_INTO_STATE = 'SET_QUIZ_INTO_STATE'
export const SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER'
export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE'
export const INPUT_Q_CHANGE = 'INPUT_Q_CHANGE'
export const INPUT_T_CHANGE = 'INPUT_T_CHANGE'
export const INPUT_F_CHANGE = 'INPUT_F_CHANGE'
export const RESET_FORM = 'RESET_FORM'
